[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_ark_foundation_veterinary = "4kc8V5wtEu9fGsjyP9RoHRmFp1hREJkmfZ7MJpR57Eva"
solana_ark_foundation_animal = "2huNFvFJBZvTqEwCjb2ZPExdGNfPdFnvNHghuAMUnzSw"
solana_ark_foundation_owner = "2huNFvFJBZvTqEwCjb2ZPExdGNfPdFnvNHghuAMUnzSw"

[registry]
url = "https://api.apr.dev"

[provider]
## cluster = "Devnet"
cluster = "http://127.0.0.1:8898"
wallet = "~/.solana/.config/keypari.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
