[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_ark_foundation_pilot = "C6HAkzF97sCRkzFp83ScP84bctYJisn479WWEZ6GEVL6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
