[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_ark_foundation_veterinary = "FaeFRU52JE9MKpQuq1EznrZBRBVAEb8vR5gu7XnDuHbg"
solana_ark_foundation_animal = "DZHj23G3RkSSZQ6pA9CWGYopCuFnUZ8WGJcnGnrVRY1i"
solana_ark_foundation_owner = "Ctjucr5AAqnJkooGQS4WYbbpqyv9cg1srvi93ucSffKn"

[registry]
url = "https://api.apr.dev"

[provider]
## cluster = "Devnet"
cluster = "http://127.0.0.1:8898"
wallet = "~/.solana/.config/keypari.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
