[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm = "3nPxt9J1Tpf7UzGmhTUW9NxsDHQKWhZrf3MGXjvcwSz9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.solana/.config/keypari.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
